### ISSUE TITLE
[Tajo JDBC Driver] 번역 task 할당 요청

### ISSUE THREAD

**Issue by sjyun** [hyunsik/tajo-doc-kr#12]
tajo jdbc Driver에 대한 번역을 진행하려고 합니다.

확인 부탁드려요.

**Comment by hyunsik** [comment]
넵 진행하시면 됩니다 :) 감사합니다.

**Comment by dongjoon-hyun** [comment]
안녕하세요. @sjyun, @hyunsik 님.

이슈가 할당되어 있던데, 진전이 안된 것 같길래, 제가 한 파일이 있어서 pull request 드렸습니다.

https://github.com/hyunsik/tajo-doc-kr/pull/24

혹시 선 진행된 결과물이 있다면, 제건 무시하셔도 됩니다. 아무쪼록 양해를 부탁 드립니다.

**Comment by sjyun** [comment]
아닙니다 그때 제가 git 경험이 없어가지고요
고생많으셨습니다
감사합니다
2015. 3. 9. 오전 11:20에 "Dongjoon Hyun" <notifications@github.com>님이 작성:

**Comment by dongjoon-hyun** [comment]
아. 다행입니다. @sjyun 님 감사합니다.

**Comment by hyunsik** [comment]
커밋되어서 이슈를 닫습니다.
