### ISSUE TITLE
Getting started page 번역

### ISSUE THREAD

**Issue by hyunsik** [hyunsik/tajo-doc-kr#2]
Getting Started 페이지를 번역합니다. 아무래도 이 문서가 초심자에게 많이 읽히기 때문에 초반에 번역하기 좋지 않나 생각합니다.
http://tajo.apache.org/docs/devel/getting_started.html

현재 여러 페이지로 분할되어 있는데요. 아래 pull request를 참고해서 한 페이지로 합쳐서 번역되면 좋을 것 같습니다.
https://github.com/apache/tajo/pull/324

**Comment by jsjang0070** [comment]
어떻게 issue owner 할당 하나요? 이 이슈를 저한테 할당하려고 합니다.

**Comment by hyunsik** [comment]
넵 막 Collaborators로 등록했습니다. 이제 스스로 할당 하실 수 있습니다 :)

**Comment by jsjang0070** [comment]
감사합니다~!

**Comment by jsjang0070** [comment]
pull request 할때 연동하는 방법이 있을 것 같은데, 함 찾아 봐야 겠네요. 아래 pull request 드렸습니다.
https://github.com/hyunsik/tajo-doc-kr/pull/6

**Comment by hyunsik** [comment]
네 보니까 아래 설명대로 하면 되는 것 같습니다. 저도 몰라서 찾아봤네요 :)
http://stackoverflow.com/a/7189981/2585750

이 이슈는 해결됐으므로 close 하겠습니다. 공헌 감사드립니다.

**Comment by hyunsik** [comment]
아래와 같이 이쁘게 잘 출력되었습니다. 공헌 해주신 덕분에 Tajo 처음 접하는 분들이 쉽게 배울 수 있을 것 같습니다!
http://hyunsik.github.io/tajo-doc-kr/docs/0.10.0/getting_started.html

**Comment by jsjang0070** [comment]
감사합니다~ :doc: 부분이 처리가 안되던데, 그 부분인거 같네요.
