### ISSUE TITLE
번역 프로젝트 신청합니다.

### ISSUE THREAD

**Issue by chowon104** [hyunsik/tajo-doc-kr#29]
안녕하세요. Apache Tajo Manual 을 번역하며 공부해보고 싶어 번역 프로젝트를 신청합니다.
감사합니다.

**Comment by hyunsik** [comment]
네 안녕하세요?

네 메일로 답변 드린 분인 것 같네요.
조만간 0.11 릴리즈 관련해서 번역 작업을 시작할 예정입니다.

아래 메일링 리스트 우선 가입해주시면 조만간 소식 전달하도록 하겠습니다.
https://groups.google.com/forum/#!forum/tajo-doc-kr/new

최현식 드림
