### ISSUE TITLE
SQL 부분에 대한 번역은 제가 진행해보겠습니다.

### ISSUE THREAD

**Issue by RonyMin** [hyunsik/tajo-doc-kr#5]
새해 복 많이 받으세요.^^

**Comment by RonyMin** [comment]
정확한 부분의 SQL Language 입니다.

**Comment by hyunsik** [comment]
넵 :) 감사합니다.

**Comment by hyunsik** [comment]
새해 복 많이 받으세요!! :)

**Comment by RonyMin** [comment]
sql_language 부분에 대한 번역을 방금 push 했습니다. 찾지 못한 오타나 어색한 표현이 있다면 comment 주시면 감사하겠습니다.

**Comment by hyunsik** [comment]
안녕하세요? 앗 감사합니다. 폭풍 번역을 ㅎㅎ 
넵 pull request로 해주시면 리뷰 보기가 좋을 것 같습니다.

감사드립니다!

**Comment by hyunsik** [comment]
네 아래와 같이 갱신되었습니다. 감사합니다. 이슈는 닫겠습니다.
http://hyunsik.github.io/tajo-doc-kr/docs/0.10.0/sql_language/data_model.html
