### ISSUE TITLE
Configuration 번역

### ISSUE THREAD

**Issue by jsjang0070** [hyunsik/tajo-doc-kr#8]

**Comment by jsjang0070** [comment]
worker를 작업 노드로 번역을 하는게 좋을까요? 아님 워커로 하는게 좋을 까요? 아님 다른 좋은 의견 부탁드립니다.

**Comment by hyunsik** [comment]
제 관점에서는 워커가 더 직관적인 것 같습니다 :)

**Comment by jsjang0070** [comment]
얍얍 알겠습니다. 감사합니다.

**Comment by jsjang0070** [comment]
https://github.com/hyunsik/tajo-doc-kr/pull/7 pull request 드렸습니다.

작업하면서 내용이 준비 안된/덜된 것으로 판단되는 페이지/내용 보고드립니다.
- catalog_configuration.rst 에 링크 [Default Ports](#DefaultPorts)
- service_config_defaults.rst 페이지 내용
- tajo-site-xml.rst 페이지 내용
- catalog-site-xml.rst 페이지 내용

**Comment by jsjang0070** [comment]
머지 후 request 스스로 처리하였습니다.
